fail_fast: true
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: master
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: master
    hooks:
      - id: pylint
        language_version: python3.7
