fail_fast: true
repos:
  - repo: local
    hooks:
    - id: autopep8
      name: AutoPep8
      entry: python -m autopep8 --in-place
      language: system
      types: [python]
  - repo: local
    hooks:
    - id: pylint
      name: PyLint
      entry: python -m pylint
      language: system
      types: [python]
